### ISSUE TITLE
Additions and removals

### ISSUE THREAD

**Issue by DLBPointon** [DLBPointon/Rainbow-Poem#1]
- [x] 1. Add beige, ivory and khaki.
- [x] 2. Remove primary colours.
- [x] 3. Discuss the merits of the colour grey.

**Comment by DLBPointon** [comment]
Merits of grey:
1, Multiple shades.
2, Easy to compliment with another colour.
3, Easier readability on coloured backgrounds.

**Comment by DLBPointon** [comment]
Branch Dull created for future saves

**Comment by DLBPointon** [comment]
The the previous commit to the above (hash = 1dfb83cdbce0bec1e36dc5f0c6f4b41e33840ac2) added Ivory, Khaki and Beige.

**Comment by DLBPointon** [comment]
Merged at hash 6bbb8af

**Comment by osmart** [comment]
> The the previous commit to the above (hash = [1dfb83c](https://github.com/DLBPointon/Rainbow-Poem/commit/1dfb83cdbce0bec1e36dc5f0c6f4b41e33840ac2)) added Ivory, Khaki and Beige.

Good if you forget to include an issue # in commit you can use the hash. No need to create a link simply copy the hash and GitHub will mark it up. For your commit if you include the complete hash text
```
1dfb83cdbce0bec1e36dc5f0c6f4b41e33840ac2 
```
Then GitHub will give a neat link: 1dfb83cdbce0bec1e36dc5f0c6f4b41e33840ac2
