### ISSUE TITLE
I think that black is a good colour!

### ISSUE THREAD

**Issue by osmart** [DLBPointon/Rainbow-Poem#3]
And
https://en.wikipedia.org/wiki/Black_Square_(painting)
is the best painting ever!

The poem would be much improved by mentioning black.

Will fork your repo and suggest an improvement.

**Comment by osmart** [comment]
Notice in the commit message I used the text `#3` this has been rendered showing the issue is on  your upstream repository and not the fork.

Click on the commit dbb4153 and you will see it is in the fork repo.

**Comment by DLBPointon** [comment]
Your addition of black to the poem has been merged with the master branch #4
